# Generated by Django 5.2.12 on 2026-04-07 00:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_type', models.CharField(choices=[('fitness', '💪 Body & Fitness'), ('finance', '💰 Financial Growth'), ('skills', '🎓 Skill Development'), ('health', '🧘 Health & Wellness'), ('relationships', '❤️ Relationships'), ('career', '💼 Career Progress'), ('mindfulness', '🧠 Mindfulness'), ('creativity', '🎨 Creative Pursuits'), ('custom', '✨ Custom Goal')], max_length=50)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('why_statement', models.TextField(blank=True)),
                ('icon', models.CharField(default='target', max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('default_activities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Life Aspects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.lifeaspect')),
            ],
            options={
                'verbose_name_plural': 'Daily Activities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('streak_3', '3 Day Streak'), ('streak_7', '7 Day Streak'), ('streak_14', '14 Day Streak'), ('streak_30', '30 Day Streak'), ('week_perfect', 'Perfect Week'), ('week_3_perfect', '3 Perfect Weeks'), ('halfway', 'Halfway Point'), ('final_week', 'Final Week'), ('completed', 'Goal Completed'), ('comeback', 'Comeback After Miss')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('badge_icon', models.CharField(default='trophy', max_length=50)),
                ('badge_color', models.CharField(default='#FFD700', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='api.lifeaspect')),
            ],
            options={
                'ordering': ['achieved', '-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyWrapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('total_days', models.IntegerField(default=7)),
                ('locked_in_days', models.IntegerField(default=0)),
                ('total_activities', models.IntegerField(default=0)),
                ('completed_activities', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('longest_streak_this_week', models.IntegerField(default=0)),
                ('ended_week_on_streak', models.BooleanField(default=False)),
                ('previous_week_completion_rate', models.FloatField(blank=True, null=True)),
                ('improvement_percentage', models.FloatField(blank=True, null=True)),
                ('reflection_notes', models.TextField(blank=True, null=True)),
                ('proudest_moment', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_wraps', to='api.lifeaspect')),
            ],
            options={
                'verbose_name_plural': 'Weekly Wraps',
                'ordering': ['-week_number'],
            },
        ),
        migrations.AddIndex(
            model_name='lifeaspect',
            index=models.Index(fields=['user', 'status'], name='api_lifeasp_user_id_2eab0b_idx'),
        ),
        migrations.AddIndex(
            model_name='lifeaspect',
            index=models.Index(fields=['user', 'is_active'], name='api_lifeasp_user_id_610914_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['aspect', 'date'], name='api_dailyac_aspect__e1dd81_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['aspect', 'date', 'completed'], name='api_dailyac_aspect__76f1e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestone',
            unique_together={('aspect', 'milestone_type')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'date'], name='api_task_user_id_807a40_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'completed'], name='api_task_user_id_5e79a6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'date', 'completed'], name='api_task_user_id_1f6e49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklywrapped',
            unique_together={('aspect', 'week_number')},
        ),
    ]
