# Generated by Django 5.2.5 on 2026-04-10 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeaspect',
            name='aspect_type',
            field=models.CharField(choices=[('fitness', 'Body & Fitness'), ('finance', 'Financial Growth'), ('skills', 'Skill Development'), ('health', 'Health & Wellness'), ('relationships', 'Relationships'), ('career', 'Career Progress'), ('mindfulness', 'Mindfulness'), ('creativity', 'Creative Pursuits'), ('custom', 'Custom Goal')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='lifeaspect',
            constraint=models.UniqueConstraint(condition=models.Q(('aspect_type', 'custom'), _negated=True), fields=('user', 'aspect_type'), name='unique_user_aspect_type'),
        ),
    ]
